<a href="https://colab.research.google.com/github/ksnugroho/teori-praktik-cv-part1/blob/main/Bagian_1_Bab_2_2_2_Menginisialisasi_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.5.1+cu121'

In [2]:
x = torch.tensor([[1,2]])
y = torch.tensor([[1],[2]])

In [3]:
print(x.shape)
print(y.shape)
print(x.dtype)

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [4]:
x = torch.tensor([False, 1, 2.0])
print(x)

tensor([0., 1., 2.])


In [5]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
torch.randint(low=0, high=10, size=(3, 4))

tensor([[0, 5, 0, 7],
        [0, 2, 7, 1],
        [7, 3, 7, 5]])

In [8]:
torch.rand(3, 4)

tensor([[0.2775, 0.9359, 0.5180, 0.2535],
        [0.2664, 0.2307, 0.1800, 0.9304],
        [0.2308, 0.1181, 0.5606, 0.7612]])

In [9]:
torch.rand((3, 4))

tensor([[0.2768, 0.2341, 0.4736, 0.8418],
        [0.8578, 0.4670, 0.5285, 0.5734],
        [0.3067, 0.1936, 0.2145, 0.2219]])

In [10]:
import numpy as np

x = np.array([[10,20,30],[2,3,4]])
y = torch.tensor(x)

print(type(x), type(y))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
